-- Agent configurations
create table "public"."agent_configs" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "name" text not null,
    "api_used" text not null,
    "model_type" text not null default 'gemini-2.5-flash',
    "status" text not null default 'stopped',
    "gemini_api_key" text,
    "github_token" text,
    "generation_frequency" text not null default 'manual',
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);

alter table "public"."agent_configs" enable row level security;

CREATE UNIQUE INDEX agent_configs_pkey ON public.agent_configs USING btree (id);

alter table "public"."agent_configs" add constraint "agent_configs_pkey" PRIMARY KEY using index "agent_configs_pkey";

alter table "public"."agent_configs" add constraint "agent_configs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) on delete cascade not valid;

alter table "public"."agent_configs" validate constraint "agent_configs_user_id_fkey";

alter table "public"."agent_configs" add constraint "agent_configs_status_check" CHECK (status = ANY (ARRAY['running', 'stopped', 'error'])) not valid;

alter table "public"."agent_configs" validate constraint "agent_configs_status_check";

alter table "public"."agent_configs" add constraint "agent_configs_frequency_check" CHECK (generation_frequency = ANY (ARRAY['manual', '1h', '3h', '6h', '12h', '24h'])) not valid;

alter table "public"."agent_configs" validate constraint "agent_configs_frequency_check";

-- Agent logs (real-time)
create table "public"."agent_logs" (
    "id" bigint generated by default as identity not null,
    "agent_id" uuid not null,
    "message" text not null,
    "level" text not null default 'info',
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
);

alter table "public"."agent_logs" enable row level security;

CREATE UNIQUE INDEX agent_logs_pkey ON public.agent_logs USING btree (id);

alter table "public"."agent_logs" add constraint "agent_logs_pkey" PRIMARY KEY using index "agent_logs_pkey";

alter table "public"."agent_logs" add constraint "agent_logs_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES agent_configs(id) on delete cascade not valid;

alter table "public"."agent_logs" validate constraint "agent_logs_agent_id_fkey";

-- Repository analyses for documentation generation
create table "public"."repository_analyses" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "repo_owner" text not null,
    "repo_name" text not null,
    "repo_url" text not null,
    "analysis_data" jsonb,
    "documentation" text,
    "status" text not null default 'pending',
    "error_message" text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);

alter table "public"."repository_analyses" enable row level security;

CREATE UNIQUE INDEX repository_analyses_pkey ON public.repository_analyses USING btree (id);

alter table "public"."repository_analyses" add constraint "repository_analyses_pkey" PRIMARY KEY using index "repository_analyses_pkey";

alter table "public"."repository_analyses" add constraint "repository_analyses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) on delete cascade not valid;

alter table "public"."repository_analyses" validate constraint "repository_analyses_user_id_fkey";

-- RLS Policies for agent_configs
create policy "Users can view their own agent configs"
on "public"."agent_configs"
as permissive
for select
to public
using ((auth.uid() = user_id));

create policy "Users can create their own agent configs"
on "public"."agent_configs"
as permissive
for insert
to public
with check ((auth.uid() = user_id));

create policy "Users can update their own agent configs"
on "public"."agent_configs"
as permissive
for update
to public
using ((auth.uid() = user_id));

create policy "Users can delete their own agent configs"
on "public"."agent_configs"
as permissive
for delete
to public
using ((auth.uid() = user_id));

-- RLS Policies for agent_logs
create policy "Users can view logs of their agents"
on "public"."agent_logs"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM agent_configs
  WHERE ((agent_configs.id = agent_logs.agent_id) AND (agent_configs.user_id = auth.uid())))));

create policy "Users can insert logs for their agents"
on "public"."agent_logs"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM agent_configs
  WHERE ((agent_configs.id = agent_logs.agent_id) AND (agent_configs.user_id = auth.uid())))));

-- RLS Policies for repository_analyses
create policy "Users can view their own analyses"
on "public"."repository_analyses"
as permissive
for select
to public
using ((auth.uid() = user_id));

create policy "Users can create their own analyses"
on "public"."repository_analyses"
as permissive
for insert
to public
with check ((auth.uid() = user_id));

create policy "Users can update their own analyses"
on "public"."repository_analyses"
as permissive
for update
to public
using ((auth.uid() = user_id));

-- Enable realtime for agent_logs
alter publication supabase_realtime add table agent_logs;

-- Grants
grant delete on table "public"."agent_configs" to "anon";
grant insert on table "public"."agent_configs" to "anon";
grant references on table "public"."agent_configs" to "anon";
grant select on table "public"."agent_configs" to "anon";
grant trigger on table "public"."agent_configs" to "anon";
grant truncate on table "public"."agent_configs" to "anon";
grant update on table "public"."agent_configs" to "anon";

grant delete on table "public"."agent_configs" to "authenticated";
grant insert on table "public"."agent_configs" to "authenticated";
grant references on table "public"."agent_configs" to "authenticated";
grant select on table "public"."agent_configs" to "authenticated";
grant trigger on table "public"."agent_configs" to "authenticated";
grant truncate on table "public"."agent_configs" to "authenticated";
grant update on table "public"."agent_configs" to "authenticated";

grant delete on table "public"."agent_logs" to "anon";
grant insert on table "public"."agent_logs" to "anon";
grant references on table "public"."agent_logs" to "anon";
grant select on table "public"."agent_logs" to "anon";
grant trigger on table "public"."agent_logs" to "anon";
grant truncate on table "public"."agent_logs" to "anon";
grant update on table "public"."agent_logs" to "anon";

grant delete on table "public"."agent_logs" to "authenticated";
grant insert on table "public"."agent_logs" to "authenticated";
grant references on table "public"."agent_logs" to "authenticated";
grant select on table "public"."agent_logs" to "authenticated";
grant trigger on table "public"."agent_logs" to "authenticated";
grant truncate on table "public"."agent_logs" to "authenticated";
grant update on table "public"."agent_logs" to "authenticated";

grant delete on table "public"."repository_analyses" to "anon";
grant insert on table "public"."repository_analyses" to "anon";
grant references on table "public"."repository_analyses" to "anon";
grant select on table "public"."repository_analyses" to "anon";
grant trigger on table "public"."repository_analyses" to "anon";
grant truncate on table "public"."repository_analyses" to "anon";
grant update on table "public"."repository_analyses" to "anon";

grant delete on table "public"."repository_analyses" to "authenticated";
grant insert on table "public"."repository_analyses" to "authenticated";
grant references on table "public"."repository_analyses" to "authenticated";
grant select on table "public"."repository_analyses" to "authenticated";
grant trigger on table "public"."repository_analyses" to "authenticated";
grant truncate on table "public"."repository_analyses" to "authenticated";
grant update on table "public"."repository_analyses" to "authenticated";
